function detectCSSFeature(featurename){"use strict";var feature=!1,domPrefixes='Webkit Moz ms O'.split(' '),elm=document.createElement('div'),featurenameCapital=null;featurename=featurename.toLowerCase();if(elm.style[featurename]){feature=!0}
if(feature===!1){featurenameCapital=featurename.charAt(0).toUpperCase()+featurename.substr(1);for(var i=0;i<domPrefixes.length;i++){if(elm.style[domPrefixes[i]+featurenameCapital]!==undefined){feature=!0;break}}}
return feature}
var hasCssTransitionSupport=detectCSSFeature("transition");var BK_CSS3="";var BK_jQueryOnly="false";if(location.href.indexOf("?jquery")!==-1){BK_jQueryOnly="true"}
if(hasCssTransitionSupport&&BK_jQueryOnly==="false"){BK_CSS3="enabled";$('.fade_effect').addClass('BK_OverThumb')}else{BK_CSS3="disabled"}
jQuery.easing.def="easeOutExpo";function PreventAllRightClick(){"use strict";$(document).ready(function(){$(document).live("contextmenu",function(e){return!1})})}
function PreventImageRightClick(){"use strict";$('img').on('contextmenu',function(event){event.preventDefault()})}
PreventImageRightClick();function PreventImageDrag(){"use strict";$('img').on('dragstart',function(event){event.preventDefault()})}
PreventImageDrag();if(BK_CSS3==="enabled"){}else{$(".fade_effect_jq").css("opacity","1.0");$(".fade_effect_jq").hover(function(){"use strict";$(this).stop().animate({opacity:1.0,width:($(this).width()*0.95),height:($(this).height()*0.95)},"fast")},function(){"use strict";$(this).stop().animate({opacity:1.0,width:($(this).width()*1.05),height:($(this).height()*1.05)},"fast")})}
if(navigator.userAgent.match(/AppleWebKit/)&&!navigator.userAgent.match(/Chrome/)){$(".fade_effect").addClass("safari")}
function getParameterByName(name){"use strict";name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "))}
var MenuDisable=getParameterByName('menu');if(MenuDisable==="undefined"||MenuDisable==="null"||MenuDisable===""){}else if(MenuDisable==="false"||MenuDisable==="f"){$("#header").css("display","none")}
var MoreDisable=getParameterByName('more');if(MoreDisable==="undefined"||MoreDisable==="null"||MoreDisable===""){}else if(MoreDisable==="false"||MoreDisable==="f"){$("#show_more").css("display","none")}
var LANG=getParameterByName('language');var DisplayTitle=getParameterByName('title');var DisplayLogo=getParameterByName('logo');var DisplayURL=getParameterByName('url');if(/[?&]title=/.test(location.search)===!1&&/[?&]logo=/.test(location.search)===!1&&/[?&]url=/.test(location.search)===!1){$("#additional").css("display","none")}
var WISEreplace="BROUGHT TO YOU LOCALLY ON FORT WAYNE'S NBC BY:";if(DisplayTitle==="undefined"||DisplayTitle==="null"||DisplayTitle===""){document.getElementsByClassName("station")[0].innerHTML="XXXX"}else if(DisplayTitle==="WISE"){document.getElementsByClassName("station_title")[0].innerHTML=WISEreplace}else{document.getElementsByClassName("station")[0].innerHTML=DisplayTitle}
if(DisplayLogo==="undefined"||DisplayLogo==="null"||DisplayLogo===""){document.getElementsByClassName("station_logo")[0].innerHTML="<img src='images/NBC_PYE_2018_255.svg' width='100%' class='rounded-img' alt=''>"}else{document.getElementsByClassName("station_logo")[0].innerHTML="<img src='"+DisplayLogo+"' width='100%' class='rounded-img' alt=''>"}
if(DisplayURL==="undefined"||DisplayURL==="null"||DisplayURL===""){DisplayURL="http://www.nbcolympics.com/"}
function checkSize(){"use strict";if(MenuDisable==="false"||MenuDisable==="f"){}}
$(document).ready(function(){"use strict";checkSize();$(window).resize(checkSize)});function move(){"use strict";var elem=document.getElementById("myBar");var width=10;var id=setInterval(frame,10);function frame(){if(width>=100){clearInterval(id)}else{width++;elem.style.width=width+'%';document.getElementById("label").innerHTML=width*1+'%'}}}
function RunJSON(how_many){"use strict";var my_json;var obj;var my_url;var GamesYear="2018";if(LANG==="undefined"||LANG==="null"||LANG===""){my_url="//api-gracenote.nbcolympics.com/svc/Games_v2.svc/Json/GetMedalTable_Season?season=20172018&languageCode=2&competitionSetId=2";$('#show_more').html("EXPAND FOR THE FULL MEDAL COUNT<br>OF THE "+GamesYear+" WINTER GAMES")}else if(LANG==="esp"||LANG==="sp"||LANG==="spanish"){my_url="//api-gracenote.nbcdeportes.com/svc/Games_v2.svc/Json/GetMedalTable_Season?season=20172018&languageCode=2&competitionSetId=2";$("#title").text("MEDALLERO OLÍMPICO");$("#main_row .country_column").text("PAÍS");$("#main_row .total_column").text("TOTAL");$("#show_more").text("VER MEDALLERO COMPLETO")}else{my_url="//api-gracenote.nbcolympics.com/svc/Games_v2.svc/Json/GetMedalTable_Season?season=20172018&languageCode=2&competitionSetId=2";$('#show_more').html("EXPAND FOR THE FULL MEDAL COUNT<br>OF THE "+GamesYear+" WINTER GAMES")}
$.getJSON(my_url,function(json){my_json=JSON.stringify(json);obj=JSON.parse(my_json);obj.MedalTableNOC.sort(function(a,b){return a.n_RankTotal-b.n_RankTotal});var ii;for(ii=0;ii<obj.MedalTableNOC.length;ii++){if(obj.MedalTableNOC[ii].c_NOCShort==="USA"){var a=obj.MedalTableNOC[ii];obj.MedalTableNOC.splice(ii,1);obj.MedalTableNOC.unshift(a)}}
var i;for(i=0;i<obj.MedalTableNOC.length;i++){if(i%2===0){$("#main_row").append("<div class='dynamic_row'><div class='country_column even'>"+obj.MedalTableNOC[i].c_NOC+"</div><div class='gold_column even'>"+obj.MedalTableNOC[i].n_Gold+"</div><div class='silver_column even'>"+obj.MedalTableNOC[i].n_Silver+"</div><div class='bronze_column even'>"+obj.MedalTableNOC[i].n_Bronze+"</div><div class='total_column even'>"+obj.MedalTableNOC[i].n_Total+"</div><div style='display:block;'></div></div>")}else{$("#main_row").append("<div class='dynamic_row'><div class='country_column odd'>"+obj.MedalTableNOC[i].c_NOC+"</div><div class='gold_column odd'>"+obj.MedalTableNOC[i].n_Gold+"</div><div class='silver_column odd'>"+obj.MedalTableNOC[i].n_Silver+"</div><div class='bronze_column odd'>"+obj.MedalTableNOC[i].n_Bronze+"</div><div class='total_column odd'>"+obj.MedalTableNOC[i].n_Total+"</div><div style='display:block;'></div></div>")}}
var row_size=$("#main_row .dynamic_row").size();var x=how_many;$('#main_row .dynamic_row').not(':lt('+x+')').hide();$("#myProgress").hide();$('#show_more').click(function(){if($('#show_more').html()==="EXPAND FOR THE FULL MEDAL COUNT<br>OF THE "+GamesYear+" WINTER GAMES"){x=(x+i<=row_size)?x+i:row_size;$('#main_row .dynamic_row:lt('+x+')').show();$(this).text("SHOW LESS")}else if($('#show_more').text()==="SHOW LESS"){x=how_many;$('#main_row .dynamic_row').not(':lt('+x+')').hide();$(this).html("EXPAND FOR THE FULL MEDAL COUNT<br>OF THE "+GamesYear+" WINTER GAMES")}
if(LANG==="esp"||LANG==="sp"){if($('#show_more').text()==="VER MEDALLERO COMPLETO"){x=(x+i<=row_size)?x+i:row_size;$('#main_row .dynamic_row:lt('+x+')').show();$(this).text("MUESTRA MENOS")}else if($('#show_more').text()==="MUESTRA MENOS"){x=how_many;$('#main_row .dynamic_row').not(':lt('+x+')').hide();$(this).text("VER MEDALLERO COMPLETO")}}})})}
move();RunJSON(3);$(".station_button").click(function(e){"use strict";e.preventDefault();ga('send','event',{eventCategory:'Outbound Link',eventAction:'click',eventLabel:DisplayURL});window.open(DisplayURL)})